// デフォルトの条件に基づいて算出された不動産取引価格の数値
const DEFAULT_SElECTED_REAL_ESTATE_TRANSACTION_PRICE = 391400;
// デフォルトの条件に基づいて算出された不動産取引価格の平均の数値
const DEFAULT_AVERAGE_REAL_ESTATE_TRANSACTION_PRICE = 51318.255319148935;

// APIの指定可能年度
const START_YEAR = 2009;
const END_YEAR = 2021;

const constantList = {
  DEFAULT_SElECTED_REAL_ESTATE_TRANSACTION_PRICE,
  DEFAULT_AVERAGE_REAL_ESTATE_TRANSACTION_PRICE,
  START_YEAR,
  END_YEAR,
};

export default constantList;
